spring.application.name=learn-springboot

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.jtsboswvswhamuixbmqe&password=Norooz@555685
spring.datasource.username=postgres.jtsboswvswhamuixbmqe
spring.datasource.password=Norooz@555685
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update